version: '3'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    volumes:
      - homeassistant_config:/config
    privileged: true
    restart: unless-stopped

volumes:
  homeassistant_config: