version: '3'
services:
  # homeassistant:
  #   image: ghcr.io/home-assistant/home-assistant:2022.5.2
  #   network_mode: host
  #   volumes:
  #     - homeassistant_config:/config
  #     - /etc/localtime:/etc/localtime:ro
  #   privileged: true
  #   restart: unless-stopped
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "64mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate_storage:/media/frigate
      # - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
      #   target: /tmp/cache
      #   tmpfs:
      #     size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds    
volumes:
  # homeassistant_config:
  # frigate_config:
  frigate_storage:
