version: "3"
services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    network_mode: br0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    network_mode: br0
    ports:
      - '80:80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.proxy.dunbarfamily.xyz`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: br0
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
#  mqtt:
#    container_name: mqtt
#    build: ./mqtt
#    pull_policy: always
#    ports:
#      - 1833:1833
