version: "3.7"
services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    networks:
      vlan:
        ipv4_address: 192.168.4.250
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    network_mode: vlan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.proxy.dunbarfamily.xyz`)"
      - "traefik.http.routers.whoami.entrypoints=web"
#  nginx:
#    image: 'jc21/nginx-proxy-manager:latest'
#    restart: unless-stopped
#    network_mode: br0
#    ports:
#      - '80:80'
#      - '81:81'
#      - '443:443'
#    volumes:
#      - ./data:/data
#      - ./letsencrypt:/etc/letsencrypt
#  mqtt:
#    container_name: mqtt
#    build: ./mqtt
#    pull_policy: always
#    ports:
#      - 1833:1833

networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.4.0/24"
          ip_range: "192.168.4.0/24"
          gateway: "192.168.4.1"