version: "3"
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: br0
#    ports:
#      - '80:80'
#      - '81:81'
#      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  mqtt:
    container_name: mqtt
    build: ./mqtt
    pull_policy: always
    ports:
      - 1833:1833