- id: "1620355855241"
  alias: Day - Start
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.hue_motion_sensor_1_motion
  condition:
    - condition: state
      entity_id: input_select.home_mode
      state: "Night"
    - condition: time
      after: "6:00"
      before: "18:00"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.home_mode
      data:
        option: "Day"
  mode: single
- id: "1620355978319"
  alias: Day - Lights On
  description: ""
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: "Day"
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.day
      data:
        transition: 10
  mode: single
