- id: "1620355855247"
  alias: Evening
  description: ""
  trigger:
    - platform: time
      at: "17:30:00"
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.evening
  mode: single
